### ISSUE TITLE
Unexpected breaking change in 1.17 version

### ISSUE THREAD

**Issue by CodeLieutenant** [scylladb/gocql#626]
In the latest gocql version 1.17 there has been a breaking change which is not documented, but observed in https://github.com/scylladb/gemini/pull/564

Gemini fails to build since the signature of the function has been changed, and no upgrade path is provided

```
Error: pkg/typedef/types.go:100:80: too many arguments in call to gocql.NewNativeType
	have (number, gocql.Type, string)
	want (byte, gocql.Type)
```

**Comment by CodeLieutenant** [comment]
> It is not unexpected, in gocql we may introduce breaking API changes in minor releases, it is unfortunate situation that is not going to go away soon.

Whats the point then in having 1.x releases when it's not stable and can break at any moment.
At least provide a clear documentation what changed and how to upgrade

**Comment by dkropachev** [comment]
To upgrade you need to pick between `gocql.NewNativeType` and `gocql.NewCustomType`
